name: Run Tests
on:
    push:
        branches: [main]

jobs:
    run-Tests:

        name: Run Tests

        runs-on: Ubuntu-latest

        steps:
        - name: Checkout own Repo
          uses: actions/checkout@v2
          with:
            repository: jasmax/python-calculator

        - name: list own contents
          run: |
            ls     
        
        - name: Checkout peer repo
          uses: actions/checkout@v2
          with:
            repository: jasmax/helloworld-python

        - name: list own contents
          run: |
            ls

        - name: Create virtual environment
          run: |
            python3 -m venv venv

        - name: Install Libraries
          run: |
            source venv/bin/activate
            pip install flake8 pytest pytest-cov robotframework
            pip list
            
        - name: Run tests
          run: |
            pytest test_Calculator.py -v -cov --junitxml=report.xml
  
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v2
          if: always()
          with:
            junit_files: "report.xml"
        - name: create folder
          run: mkdir downloads
        

        - name: move files
          run: mv *.xml ./downloads
          
        - name: Upload document
          uses: actions/upload-artifact@v2
          with: 
            name: assetDocuments
            path: downloads