name: Run Tests
on:
    push:
        branches: [main]

jobs:
    run-Tests:

        name: Run Tests

        runs-on: Ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          with:
            python-version: 3.11

        - name: Install Libraries
          run: |
            pip install flake8 pytest pytest-cov robotframework

        - name: Checkout Own Repo
          uses: actions/checkout@v2
          with:
            repository: jasmax/helloworld-python

        - name: list our contents
          run: |
            ls

        - name: Run tests
          run: |
            pytest test_calculator.py -v -cov --junitxml=report.xml

        - name: move files
          run: mv *.xml ./downloads

        - name: Upload document
          uses: actions/upload-artifact@v2
          with: 
            name: assetDocuments
            path: downloads